---
image: "golang:1.13"

before_script:
  - apt-get update 

stages:
    - test
    - build

build:
    script: 
      - export GOPATH=~/go
      - export PATH=$PATH:$GOPATH/bin
      - mkdir ~/go
      - git clone https://fox-deploy-token:ba_T6YQAYVoxmba7ysYg@gitlab.com/jkwiatko/fox.git
      - cd $GOPATH/fox
      - go install 

